version: '2'
services:
    prosopografia-app:
        image: prosopografia
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://prosopografia-postgresql:5432/prosopografia
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=prosopografia-elasticsearch:9300
        ports:
            - 8080:8080
    prosopografia-postgresql:
        extends:
            file: postgresql.yml
            service: prosopografia-postgresql
    prosopografia-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: prosopografia-elasticsearch
