export * from './personaje-pr.model';
export * from './personaje-pr-popup.service';
export * from './personaje-pr.service';
export * from './personaje-pr-dialog.component';
export * from './personaje-pr-delete-dialog.component';
export * from './personaje-pr-detail.component';
export * from './personaje-pr.component';
export * from './personaje-pr.route';
export * from './datos-personales.component';
